export type PeerMessageType = 
  | 'PLAYER_PROFILE'
  | 'PICK_4_SELECTIONS'
  | 'TEAM_SELECTIONS'
  | 'SUBMIT_ACTION'
  | 'CRUSH_PROMPT'
  | 'DISABLE_ACTION_PROMPT'
  | 'KNOCKED_OUT_SWITCH_IN_PROMPT'
  | 'SWITCH_OUT_PROMPT'